version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - run:
          name: "Build Docker image"
          command: |
            docker build . -t yehonatancohen/parties247-auto:latest
      - run:
          name: "Login to Docker Hub"
          command: |
            echo ${DOCKERHUB_PASSWORD} | docker login -u yehonatancohen --password-stdin
      - run:
          name: "Push image to Docker Hub"
          command: |
            docker push yehonatancohen/parties247-auto:latest
      - run:
          name: "Run Tests in Docker"
          command: |
             docker run --rm yehonatancohen/parties247-auto:latest pytest tests/

workflows:
  build-and-deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - master
